version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: create package
          command: cd dist/my-lib && npm pack
      - run:
          name: publish package
          command: cd projects/my-lib && npm publish --registry http://localhost:4873
