version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install
          command: pwd && npm install
      - run:
          name: build
          command: pwd && npm run build
      - run:
          name: create package
          command: pwd && cd dist/my-lib && npm pack
